# Generated by Django 4.2.1 on 2023-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50, verbose_name='name 1')),
                ('name_2', models.CharField(max_length=50, verbose_name='name 2')),
            ],
        ),
    ]
