# Generated by Django 4.2.1 on 2023-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='images', verbose_name='member image')),
                ('line_1', models.CharField(max_length=40, verbose_name='line 1')),
                ('line_2', models.CharField(max_length=40, verbose_name='line 2')),
                ('line_3', models.TextField(verbose_name='line_3')),
            ],
        ),
    ]
