# Generated by Django 4.2.1 on 2023-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIconca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_name', models.CharField(max_length=30, verbose_name='button name')),
                ('icon_text_1', models.CharField(max_length=50, verbose_name='icon text 1')),
                ('icon_text_2', models.TextField(verbose_name='icon text 2')),
            ],
        ),
    ]
