# Generated by Django 4.2.1 on 2023-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='has_like',
        ),
        migrations.AddField(
            model_name='like',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
