# Generated by Django 4.2.1 on 2023-05-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_like_has_like_like_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('info1', models.CharField(max_length=100, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=100, verbose_name='Info 2')),
                ('info3', models.CharField(max_length=100, verbose_name='Info 3')),
                ('info4', models.CharField(max_length=100, verbose_name='Info 4')),
                ('info5', models.CharField(max_length=100, verbose_name='Info 5')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
        ),
        migrations.CreateModel(
            name='HomeProductTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Name')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('datetime', models.DateField(auto_now=True, verbose_name='Datetime')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.productcategory')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
