# Generated by Django 4.2.1 on 2023-05-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homecontent_homeproducttitle_hometitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='HomeProductTitle',
        ),
        migrations.DeleteModel(
            name='HomeTitle',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
