# Generated by Django 4.2.1 on 2023-05-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hometile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeTile',
            new_name='HomeTitle',
        ),
    ]
