# Generated by Django 4.2.1 on 2023-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_hometitle_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_image', models.ImageField(upload_to='images', verbose_name='images')),
                ('contact_1', models.CharField(max_length=100, verbose_name='contact 1')),
                ('contact_2', models.CharField(max_length=100, verbose_name='contact 2')),
            ],
        ),
        migrations.AlterField(
            model_name='hometitle',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
    ]
