# Generated by Django 4.2.1 on 2023-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps', models.URLField(verbose_name='map image')),
                ('info_1', models.CharField(max_length=30, verbose_name='info 1')),
                ('info_2', models.TextField(verbose_name='info 2')),
            ],
            options={
                'verbose_name': 'ContactInfo',
                'verbose_name_plural': 'ContactInfos',
            },
        ),
    ]
