# Generated by Django 4.2.1 on 2023-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_1', models.CharField(max_length=50, verbose_name='contact 1')),
                ('contact_2', models.TextField(verbose_name='contact 2')),
                ('contact_3', models.TextField(verbose_name='contact 3')),
            ],
        ),
    ]
