# Generated by Django 4.2.1 on 2023-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contacttitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutheader',
            name='name_3',
            field=models.CharField(default=1, max_length=50, verbose_name='name 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutheader',
            name='name_4',
            field=models.CharField(default=1, max_length=50, verbose_name='name 4'),
            preserve_default=False,
        ),
    ]
