# Generated by Django 4.2.1 on 2023-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_aboutheader_name_3_aboutheader_name_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title_1', models.CharField(max_length=100, verbose_name='title 1')),
                ('prod_title_2', models.CharField(max_length=100, verbose_name='title 2')),
            ],
        ),
    ]
