# Generated by Django 4.2.1 on 2023-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_producttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_image', models.ImageField(upload_to='images', verbose_name='index image')),
                ('index_info_1', models.CharField(max_length=50, verbose_name='index info 1')),
                ('index_info_2', models.CharField(max_length=50, verbose_name='index info 2')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeTitle',
        ),
    ]
